# New ports collection makefile for:	ocaml-kern
# Date created:		2012-07-27
# Whom:			Gabor Pali <pgj@FreeBSD.org>
#
# $FreeBSD$
#

PORTNAME=	ocaml-kern
CATEGORIES=	lang

MAINTAINER=	pgj@FreeBSD.org
COMMENT=	Objective Caml compiler and programming environment (kernel)

MASTERDIR=	${.CURDIR}/../ocaml

WITHOUT_X11=		yes
WITHOUT_TK=		yes
WITHOUT_THREADS=	yes
WITHOUT_CMP_LIB=	yes
WITHOUT_OPT_DEF=	yes
WITH_KERNEL=		yes

.include "${MASTERDIR}/Makefile"
